configuration:
  database:
    username: flyte
    host: postgres.flyte.svc.cluster.local
    dbname: flyte
  storage:
    type: minio
    metadataContainer: flyte
    userDataContainer: flyte
    provider: s3
    providerConfig:
      s3:
        authType: "accesskey"
        endpoint: "http://192.168.100.11:30084"
        accessKey: "minio"
        secretKey: "miniostorage"
        disableSSL: "true"
        secure: "false"
        v2Signing: "true"

  inlineSecretRef: flyte-binary-inline-config-secret
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: "http://192.168.100.11:30084"
          - FLYTE_AWS_ACCESS_KEY_ID: "minio"
          - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage"

    task_resources:
      defaults:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 3Gi

serviceAccount:
  create: true
